// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Theo_DisableTouchUI","status":true,"description":"Removes the touch UI and reposition the menu accordingly","parameters":{}},
{"name":"Fullscreen","status":true,"description":"Starts the game in fullscreen","parameters":{}},
{"name":"SplashScreen","status":true,"description":"","parameters":{}},
{"name":"TextPicture","status":false,"description":"Displays text as a picture.","parameters":{}},
{"name":"RF_CustomWindowMessage","status":false,"description":"(v.1.0) Create custom window. View documentation for plugin commands.","parameters":{}},
{"name":"TSGamepad","status":true,"description":"[v1.0] OnScreen Controls for RMMZ","parameters":{"dpad":"1","stick":"60","exten":".svg","bcAd":"#7dc242","bcBd":"#ed1c24","bcXd":"#24bcee","bcYd":"#f0ea1b"}}
];
